name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Build the Docker image for user-services
    - name: Build the Docker image for user-services
      run: docker build ./user-services --file ./user-services/Dockerfile --tag user-services:$(date +%s)
    
    # Build the Docker image for event-service
    - name: Build the Docker image for event-service
      run: docker build ./event-service --file ./event-service/Dockerfile --tag event-service:$(date +%s)
