name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    strategy:
      matrix:
        service: [user-services, order-services]  # Danh sách các service mà bạn có
        configuration: [Debug, Release]

    runs-on: windows-latest  # Dùng runner Windows

    env:
      Solution_Name: Solution.sln  # Đảm bảo đúng tên tệp solution của bạn
      Wap_Project_Directory: ${{ matrix.service }}/Package
      Wap_Project_Path: ${{ matrix.service }}/Package/${{ matrix.service }}.wapproj

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Đảm bảo tất cả các tệp đều được fetch

    # Kiểm tra nội dung thư mục để xác nhận tệp solution và các dự án
    - name: List directory contents
      run: |
        dir .  # Kiểm tra thư mục root để chắc chắn rằng Solution.sln tồn tại

    # Cài đặt .NET Core SDK
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Cài đặt MSBuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Thực thi unit tests cho tất cả các dự án trong Solution
    - name: Execute unit tests
      run: dotnet test ${{ env.Solution_Name }}

    # Restore dependencies cho tất cả các dự án
    - name: Restore dependencies
      run: msbuild ${{ env.Solution_Name }} /t:Restore /p:Configuration=${{ matrix.configuration }}

    # Tạo và đóng gói ứng dụng cho từng dịch vụ
    - name: Create the app package
      run: msbuild ${{ env.Wap_Project_Path }} /p:Configuration=${{ matrix.configuration }} /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86|x64
        Appx_Package_Build_Mode: StoreUpload
        Configuration: ${{ matrix.configuration }}

    # Xóa PFX certificate sau khi đóng gói
    - name: Remove the PFX certificate
      run: Remove-Item -path $env:Wap_Project_Directory\GitHubActionsWorkflow.pfx

    # Upload MSIX package dưới dạng artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}\AppPackages
