name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    strategy:
      matrix:
        service: [event-service, user-services]   # Chạy từng service một
        configuration: [Debug, Release]

    runs-on: windows-latest  # Chạy trên runner Windows

    env:
      # Thay đổi Solution_Name cho từng service
      Solution_Name: ${{ matrix.service }}/${{ matrix.service }}.sln
      Wap_Project_Directory: ${{ matrix.service }}/${{ matrix.service }}.Package
      Wap_Project_Path: ${{ matrix.service }}/${{ matrix.service }}.Package/${{ matrix.service }}.Package.wapproj

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Cài đặt .NET Core SDK
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Cài đặt MSBuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Chạy unit tests
    - name: Execute unit tests
      run: dotnet test ${{ env.Solution_Name }}

    # Restore dependencies cho ứng dụng
    - name: Restore dependencies
      run: msbuild ${{ env.Solution_Name }} /t:Restore /p:Configuration=${{ matrix.configuration }}

    # Giải mã PFX certificate và lưu nó vào thư mục
    - name: Decode the PFX certificate
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath GitHubActionsWorkflow.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    # Build và package dự án
    - name: Build and create app package
      run: msbuild ${{ env.Wap_Project_Path }} /p:Configuration=${{ matrix.configuration }} /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86|x64
        Appx_Package_Build_Mode: StoreUpload
        Configuration: ${{ matrix.configuration }}

    # Xóa PFX sau khi hoàn thành
    - name: Remove the PFX certificate
      run: Remove-Item -path $env:Wap_Project_Directory\GitHubActionsWorkflow.pfx

    # Upload MSIX package artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}\AppPackages
